<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use Laravel\Sanctum\HasApiTokens;
use App\Models\ReferralTransactions;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use KirschbaumDevelopment\NovaMail\Traits\Mailable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasRoles, HasApiTokens, HasFactory, Notifiable, Mailable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * Get the name of the email field for the model.
     *
     * @return string
     */
    public function getEmailField(): string
    {
        return 'email';
    }

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function referredPatients()
    {
        return $this->hasMany(Patient::class, 'referrer_id');
    }

    // public function referrals()
    // {
    //     return $this->hasMany(ReferralTransactions::class);
    // }

    // Each user has many referral transactions
    public function referralTransactions()
    {
        return $this->hasMany(ReferralTransactions::class, 'referrer_id');
    }

    public function referredBills()
    {
        return $this->hasManyThrough(
            Bills::class,
            Patient::class,
            'referrer_id', // Foreign key on patients table...
            'patient_id', // Foreign key on bills table...
            'id', // Local key on users table...
        );
    }

    // Total referral amount accrued by this user based on the referral percentage
    // of all the bills generated by patients referred by this user.
    public function totalReferralAmount()
    {
        return $this->referredBills->map(function ($bill) {
            return $bill->total_amount * ($this->referral_percentage / 100);
        })->sum();
    }

    // Sum of the total of all bills of patients referred by this user.
    public function totalBillsAmount()
    {
        return $this->referredBills()->sum('total_amount');
    }

    // Sum of the unpaid bills of patients referred by this user
    public function totalUnpaidBillsAmount()
    {
        return $this->referredBills()->where('payment_status', 'unpaid')->sum('total_amount');
    }

    // Sum of the paid bills of patients referred by this user
    public function totalPaidBillsAmount()
    {
        return $this->referredBills()->where('payment_status', 'Fully Paid')->sum('total_amount');
    }

    // Current withdrawable account balance: auto calculated referral amount (from percentage set) 
    // using the sum of all "Fully paid" bills assigned to this user.
    public function withdrawableAccountBalance()
    {
        return $this->referredBills->filter(function ($bill) {
            return $bill->payment_status == 'Fully Paid';
        })->map(function ($bill) {
            return $bill->total_amount * ($this->referral_percentage / 100);
        })->sum();
    }

    // Total lifetime withdrawn amount: sum of all "debit" referral transactions recorded for this user
    public function totalWithdrawnAmount()
    {
        return $this->referralTransactions()->where('debit_amount', '>', 0)->sum('debit_amount');
    }
    
    // Total amount paid in by this user: sum of all "credit" referral transactions recorded for this user
    public function totalPaidInAmount()
    {
        return $this->referralTransactions()->where('credit_amount', '>', 0)->sum('credit_amount');
    }

    // Code that might be useful in the future
    // public function updateAccountBalance()
    // {
    //     $totalReferralAmount = $this->totalReferralAmount();

    //     $this->referralTransactions()->update(['account_balance' => $totalReferralAmount]);
    // }
}
